apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mini-chat.fullname" . }}
  labels:
    {{- include "mini-chat.labels" . | nindent 4 }}
type: Opaque
stringData:
  azure-openai-api-key: {{ .Values.secrets.azureOpenaiApiKey | quote }}
  azure-openai-api-host: {{ .Values.secrets.azureOpenaiApiHost | quote }}
  pg-password: {{ .Values.postgres.password | quote }}
